//! Every action the TUI has, by name (§10.8): what buttons, the node menu
//! and the command palette run. Keys call the same `act_*` functions.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Action {
    // on a node
    Edit,
    Zoom,
    NewSibling,
    NewChild,
    ToggleDone,
    ToggleTask,
    Props,
    MakeBlock,
    MoveUp,
    MoveDown,
    Indent,
    Outdent,
    Respell,
    Refile,
    Archive,
    Copy,
    Delete,
    PasteAfter,
    PasteBefore,
    NodeMenu,
    // views and the vault
    ZoomOut,
    Filter,
    Palette,
    Help,
    Quit,
    Undo,
    Redo,
    Capture,
    CaptureTask,
    HideDone,
    RawMode,
    GoTo,
    ClearDone,
    Canonicalize,
    Merge,
    ResolveConflicts,
    // editor
    EditDone,
    EditRevert,
    // popups
    Close,
    PromptOk,
    PropAdd,
    ConflictOurs,
    ConflictTheirs,
    ConflictBoth,
    ConflictEdit,
    ConflictPrev,
    ConflictNext,
}

impl Action {
    /// The name shown in menus and the palette.
    pub fn label(self) -> &'static str {
        use Action::*;
        match self {
            Edit => "Edit",
            Zoom => "Zoom in",
            NewSibling => "New sibling",
            NewChild => "New child",
            ToggleDone => "Done / reopen",
            ToggleTask => "Task on / off",
            Props => "Properties…",
            MakeBlock => "Make block",
            MoveUp => "Move up",
            MoveDown => "Move down",
            Indent => "Indent",
            Outdent => "Outdent",
            Respell => "Heading ↔ bullet",
            Refile => "Move to…",
            Archive => "Archive",
            Copy => "Copy",
            Delete => "Delete",
            PasteAfter => "Paste after",
            PasteBefore => "Paste before",
            NodeMenu => "Node menu",
            ZoomOut => "Zoom out",
            Filter => "Filter",
            Palette => "Commands",
            Help => "Help",
            Quit => "Quit",
            Undo => "Undo",
            Redo => "Redo",
            Capture => "Capture",
            CaptureTask => "Capture task",
            HideDone => "Hide / show done",
            RawMode => "Raw / styled",
            GoTo => "Go to…",
            ClearDone => "Clear done",
            Canonicalize => "Canonicalize",
            Merge => "Merge sync conflicts",
            ResolveConflicts => "Resolve conflicts",
            EditDone => "Done",
            EditRevert => "Revert",
            Close => "Close",
            PromptOk => "OK",
            PropAdd => "Add",
            ConflictOurs => "Keep ours",
            ConflictTheirs => "Keep theirs",
            ConflictBoth => "Keep both",
            ConflictEdit => "Edit ours",
            ConflictPrev => "Previous",
            ConflictNext => "Next",
        }
    }

    /// A one-cell icon for compact buttons.
    pub fn icon(self) -> Option<&'static str> {
        use Action::*;
        Some(match self {
            Edit => "✎",
            Filter => "⌕",
            Palette => "☰",
            Help => "?",
            Undo => "↶",
            Redo => "↷",
            Capture => "+",
            EditDone => "✓",
            EditRevert => "↺",
            NodeMenu => "⋯",
            Close => "✕",
            PropAdd => "+",
            ConflictPrev => "◀",
            ConflictNext => "▶",
            _ => return None,
        })
    }

    /// The key that does the same, shown beside the label.
    pub fn key(self) -> Option<&'static str> {
        use Action::*;
        Some(match self {
            Edit => "e",
            Zoom => "Enter",
            NewSibling => "n",
            NewChild => "N",
            ToggleDone => "x",
            ToggleTask => "t",
            Props => "a",
            MakeBlock => "s",
            MoveUp => "K",
            MoveDown => "J",
            Indent => ">",
            Outdent => "<",
            Respell => "~",
            Refile => "r",
            Archive => "za",
            Copy => "y",
            Delete => "d",
            PasteAfter => "p",
            PasteBefore => "P",
            NodeMenu => "m",
            ZoomOut => "Bksp",
            Filter => "/",
            Palette => ":",
            Help => "?",
            Quit => "q",
            Undo => "u",
            Redo => "U",
            Capture => "c",
            CaptureTask => "C",
            HideDone => "zd",
            RawMode => "zr",
            EditDone => "Esc",
            EditRevert => "Ctrl-c",
            Close => "Esc",
            PromptOk => "Enter",
            ConflictOurs => "o",
            ConflictTheirs => "t",
            ConflictBoth => "b",
            ConflictEdit => "e",
            ConflictPrev => "N",
            ConflictNext => "n",
            _ => return None,
        })
    }

    /// What it does, for the palette.
    pub fn desc(self) -> &'static str {
        use Action::*;
        match self {
            Edit => "edit the subtree's Markdown",
            Zoom => "read this node on its own",
            NewSibling => "insert an empty node after this one",
            NewChild => "insert an empty last child",
            ToggleDone => "check or uncheck the task",
            ToggleTask => "add or remove the checkbox",
            Props => "edit the node's properties",
            MakeBlock => "give the node its own file",
            MoveUp => "swap with the previous sibling",
            MoveDown => "swap with the next sibling",
            Indent => "become the last child of the previous sibling",
            Outdent => "become the next sibling of the parent",
            Respell => "toggle heading / bullet spelling",
            Refile => "move the subtree under another node",
            Archive => "move the subtree under # Archive",
            Copy => "copy the subtree",
            Delete => "move the subtree to the trash",
            PasteAfter => "paste the copied subtree after this node",
            PasteBefore => "paste the copied subtree before this node",
            NodeMenu => "every action on the selected node",
            ZoomOut => "up one level",
            Filter => "find nodes by title and text",
            Palette => "every action by name",
            Help => "how to use fold",
            Quit => "save and exit",
            Undo => "undo the last change",
            Redo => "redo the last undone change",
            Capture => "append a note to today's inbox",
            CaptureTask => "append a task to today's inbox",
            HideDone => "hide or show finished tasks",
            RawMode => "show the exact source",
            GoTo => "jump to a node",
            ClearDone => "trash finished tasks under the zoom",
            Canonicalize => "rewrite the vault in canonical form",
            Merge => "fold sync-conflict files in",
            ResolveConflicts => "review conflict pairs",
            EditDone => "save and leave the editor",
            EditRevert => "drop changes since the last save",
            Close => "close",
            PromptOk => "accept",
            PropAdd => "add a property",
            ConflictOurs => "keep this device's version",
            ConflictTheirs => "keep the other device's version",
            ConflictBoth => "keep both as siblings",
            ConflictEdit => "edit this device's version",
            ConflictPrev => "previous pair",
            ConflictNext => "next pair",
        }
    }
}

/// The node menu (right-click, `⋯`, `m`): `None` is a separator.
pub const NODE_MENU: &[Option<Action>] = &[
    Some(Action::Edit),
    Some(Action::Zoom),
    Some(Action::Props),
    None,
    Some(Action::NewSibling),
    Some(Action::NewChild),
    None,
    Some(Action::ToggleDone),
    Some(Action::ToggleTask),
    Some(Action::Respell),
    Some(Action::MakeBlock),
    None,
    Some(Action::MoveUp),
    Some(Action::MoveDown),
    Some(Action::Indent),
    Some(Action::Outdent),
    Some(Action::Refile),
    Some(Action::Archive),
    None,
    Some(Action::Copy),
    Some(Action::PasteAfter),
    Some(Action::PasteBefore),
    Some(Action::Delete),
];

/// Everything in the command palette, in order.
pub const PALETTE: &[Action] = &[
    Action::Edit,
    Action::Zoom,
    Action::ZoomOut,
    Action::GoTo,
    Action::Filter,
    Action::NewSibling,
    Action::NewChild,
    Action::ToggleDone,
    Action::ToggleTask,
    Action::Props,
    Action::MakeBlock,
    Action::Respell,
    Action::MoveUp,
    Action::MoveDown,
    Action::Indent,
    Action::Outdent,
    Action::Refile,
    Action::Archive,
    Action::Copy,
    Action::PasteAfter,
    Action::PasteBefore,
    Action::Delete,
    Action::Capture,
    Action::CaptureTask,
    Action::Undo,
    Action::Redo,
    Action::HideDone,
    Action::RawMode,
    Action::ClearDone,
    Action::Canonicalize,
    Action::Merge,
    Action::ResolveConflicts,
    Action::Help,
    Action::Quit,
];
