// @generated from the crates.io survey of tree-sitter grammars (see highlight.rs).
// One entry per language: its id, the names a fence may use, its parser and highlights query.

use tree_sitter::Language;

pub struct Grammar {
    pub id: &'static str,
    pub aliases: &'static [&'static str],
    pub language: fn() -> Language,
    pub highlights: fn() -> String,
}

pub const GRAMMARS: &[Grammar] = &[
    Grammar { id: "ada", aliases: &["adb", "ads"], language: || tree_sitter_ada::LANGUAGE.into(), highlights: || include_str!("../../queries/ada.scm").into() },
    Grammar { id: "agda", aliases: &[], language: || tree_sitter_agda::LANGUAGE.into(), highlights: || tree_sitter_agda::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "al", aliases: &[], language: || tree_sitter_al::LANGUAGE.into(), highlights: || tree_sitter_al::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "applesoft", aliases: &[], language: || tree_sitter_applesoft::LANGUAGE.into(), highlights: || include_str!("../../queries/applesoft.scm").into() },
    Grammar { id: "arduino", aliases: &["ino"], language: || tree_sitter_arduino::LANGUAGE.into(), highlights: || tree_sitter_arduino::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "arkts", aliases: &["ets"], language: || tree_sitter_arkts::LANGUAGE.into(), highlights: || tree_sitter_arkts::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "asm", aliases: &["assembly", "nasm", "gas", "s"], language: || tree_sitter_asm::LANGUAGE.into(), highlights: || tree_sitter_asm::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "astro", aliases: &[], language: || tree_sitter_astro_next::LANGUAGE.into(), highlights: || tree_sitter_astro_next::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "autohotkey", aliases: &["ahk"], language: || tree_sitter_autohotkey::LANGUAGE.into(), highlights: || tree_sitter_autohotkey::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "bash", aliases: &["sh", "shell", "console", "shellsession", "ksh"], language: || tree_sitter_bash::LANGUAGE.into(), highlights: || tree_sitter_bash::HIGHLIGHT_QUERY.into() },
    Grammar { id: "batch", aliases: &["bat", "cmd", "dosbatch"], language: || tree_sitter_batch::LANGUAGE.into(), highlights: || tree_sitter_batch::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "bicep", aliases: &[], language: || tree_sitter_bicep::LANGUAGE.into(), highlights: || tree_sitter_bicep::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "c", aliases: &["h"], language: || tree_sitter_c::LANGUAGE.into(), highlights: || tree_sitter_c::HIGHLIGHT_QUERY.into() },
    Grammar { id: "csharp", aliases: &["cs", "c#"], language: || tree_sitter_c_sharp::LANGUAGE.into(), highlights: || tree_sitter_c_sharp::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "caddy", aliases: &["caddyfile"], language: || tree_sitter_caddy::LANGUAGE.into(), highlights: || include_str!("../../queries/caddy.scm").into() },
    Grammar { id: "cfml", aliases: &["cfm"], language: || tree_sitter_cfml::LANGUAGE_CFML.into(), highlights: || include_str!("../../queries/cfml.scm").into() },
    Grammar { id: "cfscript", aliases: &["cfc"], language: || tree_sitter_cfml::LANGUAGE_CFSCRIPT.into(), highlights: || include_str!("../../queries/cfscript.scm").into() },
    Grammar { id: "cfquery", aliases: &[], language: || tree_sitter_cfml::LANGUAGE_CFQUERY.into(), highlights: || include_str!("../../queries/cfquery.scm").into() },
    Grammar { id: "clojure", aliases: &["clj", "cljs", "cljc", "edn"], language: || tree_sitter_clojure_orchard::LANGUAGE.into(), highlights: || tree_sitter_clojure_orchard::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "cmake", aliases: &[], language: || tree_sitter_cmake::LANGUAGE.into(), highlights: || tree_sitter_cmake::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "dockerfile", aliases: &["docker", "containerfile"], language: || tree_sitter_containerfile::LANGUAGE.into(), highlights: || tree_sitter_containerfile::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "cpp", aliases: &["c++", "cc", "cxx", "hpp", "hh", "hxx", "h++"], language: || tree_sitter_cpp::LANGUAGE.into(), highlights: || tree_sitter_cpp::HIGHLIGHT_QUERY.into() },
    Grammar { id: "css", aliases: &[], language: || tree_sitter_css::LANGUAGE.into(), highlights: || tree_sitter_css::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "cuda", aliases: &["cu"], language: || tree_sitter_cuda::LANGUAGE.into(), highlights: || tree_sitter_cuda::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "cypher", aliases: &["cql"], language: || tree_sitter_cypher::LANGUAGE.into(), highlights: || tree_sitter_cypher::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "d", aliases: &["dlang"], language: || tree_sitter_d::LANGUAGE.into(), highlights: || include_str!("../../queries/d.scm").into() },
    Grammar { id: "dafny", aliases: &["dfy"], language: || tree_sitter_dafny::LANGUAGE.into(), highlights: || include_str!("../../queries/dafny.scm").into() },
    Grammar { id: "dart", aliases: &[], language: || tree_sitter_dart::LANGUAGE.into(), highlights: || tree_sitter_dart::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "devicetree", aliases: &["dts", "dtsi"], language: || tree_sitter_devicetree::LANGUAGE.into(), highlights: || tree_sitter_devicetree::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "diff", aliases: &["patch", "udiff"], language: || tree_sitter_diff::LANGUAGE.into(), highlights: || tree_sitter_diff::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "dm", aliases: &["dreammaker", "byond"], language: || tree_sitter_dm::LANGUAGE.into(), highlights: || include_str!("../../queries/dm.scm").into() },
    Grammar { id: "elisp", aliases: &["emacs-lisp", "el"], language: || tree_sitter_elisp::LANGUAGE.into(), highlights: || tree_sitter_elisp::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "elixir", aliases: &["ex", "exs"], language: || tree_sitter_elixir::LANGUAGE.into(), highlights: || tree_sitter_elixir::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "elm", aliases: &[], language: || tree_sitter_elm::LANGUAGE.into(), highlights: || tree_sitter_elm::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "erb", aliases: &["ejs", "eex"], language: || tree_sitter_embedded_template::LANGUAGE.into(), highlights: || tree_sitter_embedded_template::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "erlang", aliases: &["erl", "hrl"], language: || tree_sitter_erlang::LANGUAGE.into(), highlights: || tree_sitter_erlang::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "fortran", aliases: &["f90", "f95", "f03", "f08", "for"], language: || tree_sitter_fortran::LANGUAGE.into(), highlights: || tree_sitter_fortran::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "fsharp", aliases: &["fs", "f#", "fsx"], language: || tree_sitter_fsharp::LANGUAGE_FSHARP.into(), highlights: || tree_sitter_fsharp::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "fsharp-signature", aliases: &["fsi"], language: || tree_sitter_fsharp::LANGUAGE_SIGNATURE.into(), highlights: || include_str!("../../queries/fsharp-signature.scm").into() },
    Grammar { id: "gdshader", aliases: &["gdshaderinc"], language: || tree_sitter_gdshader::LANGUAGE.into(), highlights: || tree_sitter_gdshader::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "gitcommit", aliases: &["git-commit", "commit"], language: || tree_sitter_gitcommit::LANGUAGE.into(), highlights: || tree_sitter_gitcommit::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "gleam", aliases: &[], language: || tree_sitter_gleam::LANGUAGE.into(), highlights: || tree_sitter_gleam::HIGHLIGHT_QUERY.into() },
    Grammar { id: "glsl", aliases: &["vert", "frag"], language: || tree_sitter_glsl::LANGUAGE_GLSL.into(), highlights: || tree_sitter_glsl::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "go", aliases: &["golang"], language: || tree_sitter_go::LANGUAGE.into(), highlights: || tree_sitter_go::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "gomod", aliases: &["go.mod"], language: || tree_sitter_gomod_orchard::LANGUAGE.into(), highlights: || include_str!("../../queries/gomod.scm").into() },
    Grammar { id: "gosum", aliases: &["go.sum"], language: || tree_sitter_gosum_orchard::LANGUAGE.into(), highlights: || tree_sitter_gosum_orchard::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "gwbasic", aliases: &[], language: || tree_sitter_gwbasic::LANGUAGE.into(), highlights: || include_str!("../../queries/gwbasic.scm").into() },
    Grammar { id: "handlebars", aliases: &["hbs", "mustache"], language: || tree_sitter_handlebars::LANGUAGE.into(), highlights: || tree_sitter_handlebars::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "harn", aliases: &[], language: || tree_sitter_harn::LANGUAGE.into(), highlights: || tree_sitter_harn::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "haskell", aliases: &["hs"], language: || tree_sitter_haskell::LANGUAGE.into(), highlights: || tree_sitter_haskell::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "heex", aliases: &[], language: || tree_sitter_heex::LANGUAGE.into(), highlights: || tree_sitter_heex::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "html", aliases: &["htm", "xhtml"], language: || tree_sitter_html::LANGUAGE.into(), highlights: || tree_sitter_html::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "ini", aliases: &["cfg", "conf", "dosini", "editorconfig"], language: || tree_sitter_ini::LANGUAGE.into(), highlights: || tree_sitter_ini::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "ink", aliases: &[], language: || tree_sitter_ink_lbz::LANGUAGE.into(), highlights: || include_str!("../../queries/ink.scm").into() },
    Grammar { id: "integerbasic", aliases: &[], language: || tree_sitter_integerbasic::LANGUAGE.into(), highlights: || include_str!("../../queries/integerbasic.scm").into() },
    Grammar { id: "irules", aliases: &["tcl-irules"], language: || tree_sitter_irules::LANGUAGE.into(), highlights: || tree_sitter_irules::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "java", aliases: &[], language: || tree_sitter_java::LANGUAGE.into(), highlights: || tree_sitter_java::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "javadoc", aliases: &[], language: || tree_sitter_javadoc::LANGUAGE.into(), highlights: || tree_sitter_javadoc::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "javascript", aliases: &["js", "jsx", "mjs", "cjs", "node"], language: || tree_sitter_javascript::LANGUAGE.into(), highlights: || format!("{}\n{}", tree_sitter_javascript::HIGHLIGHT_QUERY, tree_sitter_javascript::JSX_HIGHLIGHT_QUERY) },
    Grammar { id: "jinja2", aliases: &["jinja", "j2", "twig"], language: || tree_sitter_jinja2::LANGUAGE.into(), highlights: || tree_sitter_jinja2::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "jsdoc", aliases: &[], language: || tree_sitter_jsdoc::LANGUAGE.into(), highlights: || tree_sitter_jsdoc::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "json", aliases: &["jsonc", "json5", "geojson"], language: || tree_sitter_json::LANGUAGE.into(), highlights: || tree_sitter_json::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "jsonnet", aliases: &["libsonnet"], language: || tree_sitter_jsonnet::LANGUAGE.into(), highlights: || tree_sitter_jsonnet::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "julia", aliases: &["jl"], language: || tree_sitter_julia::LANGUAGE.into(), highlights: || include_str!("../../queries/julia.scm").into() },
    Grammar { id: "kconfig", aliases: &[], language: || tree_sitter_kconfig::LANGUAGE.into(), highlights: || tree_sitter_kconfig::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "kotlin", aliases: &["kt", "kts"], language: || tree_sitter_kotlin_sg::LANGUAGE.into(), highlights: || tree_sitter_kotlin_sg::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "lambdamoo", aliases: &["moo"], language: || tree_sitter_lambdamoo::LANGUAGE.into(), highlights: || tree_sitter_lambdamoo::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "llvm", aliases: &["ll"], language: || tree_sitter_llvm::LANGUAGE.into(), highlights: || tree_sitter_llvm::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "lua", aliases: &[], language: || tree_sitter_lua::LANGUAGE.into(), highlights: || tree_sitter_lua::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "luau", aliases: &[], language: || tree_sitter_luau::LANGUAGE.into(), highlights: || tree_sitter_luau::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "make", aliases: &["makefile", "mk", "gnumake"], language: || tree_sitter_make::LANGUAGE.into(), highlights: || tree_sitter_make::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "matlab", aliases: &[], language: || tree_sitter_matlab::LANGUAGE.into(), highlights: || include_str!("../../queries/matlab.scm").into() },
    Grammar { id: "merlin6502", aliases: &[], language: || tree_sitter_merlin6502::LANGUAGE.into(), highlights: || include_str!("../../queries/merlin6502.scm").into() },
    Grammar { id: "mlir", aliases: &[], language: || tree_sitter_mlir::LANGUAGE.into(), highlights: || tree_sitter_mlir::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "msbasic2", aliases: &[], language: || tree_sitter_msbasic2::LANGUAGE.into(), highlights: || include_str!("../../queries/msbasic2.scm").into() },
    Grammar { id: "newick", aliases: &["nwk"], language: || tree_sitter_newick::LANGUAGE.into(), highlights: || include_str!("../../queries/newick.scm").into() },
    Grammar { id: "nginx", aliases: &[], language: || tree_sitter_nginx::LANGUAGE.into(), highlights: || include_str!("../../queries/nginx.scm").into() },
    Grammar { id: "nix", aliases: &[], language: || tree_sitter_nix::LANGUAGE.into(), highlights: || tree_sitter_nix::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "objc", aliases: &["objective-c", "objectivec", "obj-c"], language: || tree_sitter_objc::LANGUAGE.into(), highlights: || tree_sitter_objc::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "ocaml", aliases: &["ml"], language: || tree_sitter_ocaml::LANGUAGE_OCAML.into(), highlights: || tree_sitter_ocaml::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "ocaml-interface", aliases: &["mli"], language: || tree_sitter_ocaml::LANGUAGE_OCAML_INTERFACE.into(), highlights: || tree_sitter_ocaml::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "ocamllex", aliases: &["mll"], language: || tree_sitter_ocamllex::LANGUAGE.into(), highlights: || tree_sitter_ocamllex::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "odin", aliases: &[], language: || tree_sitter_odin::LANGUAGE.into(), highlights: || tree_sitter_odin::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "openscad", aliases: &["scad"], language: || tree_sitter_openscad::LANGUAGE.into(), highlights: || tree_sitter_openscad::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "pascal", aliases: &["pas", "delphi", "objectpascal"], language: || tree_sitter_pascal::LANGUAGE.into(), highlights: || include_str!("../../queries/pascal.scm").into() },
    Grammar { id: "pgn", aliases: &[], language: || tree_sitter_pgn::LANGUAGE.into(), highlights: || include_str!("../../queries/pgn.scm").into() },
    Grammar { id: "php", aliases: &[], language: || tree_sitter_php::LANGUAGE_PHP.into(), highlights: || tree_sitter_php::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "postgres", aliases: &["postgresql", "pgsql"], language: || tree_sitter_postgres::LANGUAGE.into(), highlights: || include_str!("../../queries/postgres.scm").into() },
    Grammar { id: "plpgsql", aliases: &[], language: || tree_sitter_postgres::LANGUAGE_PLPGSQL.into(), highlights: || include_str!("../../queries/plpgsql.scm").into() },
    Grammar { id: "powershell", aliases: &["ps1", "psm1", "pwsh", "posh"], language: || tree_sitter_powershell::LANGUAGE.into(), highlights: || tree_sitter_powershell::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "printf", aliases: &[], language: || tree_sitter_printf::LANGUAGE.into(), highlights: || tree_sitter_printf::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "prisma", aliases: &[], language: || tree_sitter_prisma_io::LANGUAGE.into(), highlights: || include_str!("../../queries/prisma.scm").into() },
    Grammar { id: "prolog", aliases: &[], language: || tree_sitter_prolog::LANGUAGE.into(), highlights: || tree_sitter_prolog::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "properties", aliases: &["java-properties"], language: || tree_sitter_properties::LANGUAGE.into(), highlights: || tree_sitter_properties::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "proto", aliases: &["protobuf"], language: || tree_sitter_proto::LANGUAGE.into(), highlights: || include_str!("../../queries/proto.scm").into() },
    Grammar { id: "puppet", aliases: &["pp"], language: || tree_sitter_puppet::LANGUAGE.into(), highlights: || tree_sitter_puppet::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "python", aliases: &["py", "python3", "py3", "gyp"], language: || tree_sitter_python::LANGUAGE.into(), highlights: || tree_sitter_python::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "qbasic", aliases: &["quickbasic"], language: || tree_sitter_qbasic::LANGUAGE.into(), highlights: || include_str!("../../queries/qbasic.scm").into() },
    Grammar { id: "ql", aliases: &["codeql"], language: || tree_sitter_ql::LANGUAGE.into(), highlights: || tree_sitter_ql::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "qmljs", aliases: &["qml"], language: || tree_sitter_qmljs::LANGUAGE.into(), highlights: || tree_sitter_qmljs::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "qsharp", aliases: &["qs", "q#"], language: || tree_sitter_qsharp::LANGUAGE.into(), highlights: || tree_sitter_qsharp::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "r", aliases: &["rscript"], language: || tree_sitter_r::LANGUAGE.into(), highlights: || tree_sitter_r::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "racket", aliases: &["rkt"], language: || tree_sitter_racket::LANGUAGE.into(), highlights: || tree_sitter_racket::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "regex", aliases: &["regexp"], language: || tree_sitter_regex::LANGUAGE.into(), highlights: || tree_sitter_regex::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "requirements", aliases: &["requirements.txt", "pip"], language: || tree_sitter_requirements::LANGUAGE.into(), highlights: || tree_sitter_requirements::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "riscv", aliases: &[], language: || tree_sitter_riscv::LANGUAGE.into(), highlights: || tree_sitter_riscv::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "ruby", aliases: &["rb", "gemspec", "podspec", "rake"], language: || tree_sitter_ruby::LANGUAGE.into(), highlights: || tree_sitter_ruby::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "rush", aliases: &[], language: || tree_sitter_rush::LANGUAGE.into(), highlights: || tree_sitter_rush::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "rust", aliases: &["rs"], language: || tree_sitter_rust::LANGUAGE.into(), highlights: || tree_sitter_rust::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "sas", aliases: &[], language: || tree_sitter_sas::LANGUAGE.into(), highlights: || tree_sitter_sas::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "scala", aliases: &["sc"], language: || tree_sitter_scala::LANGUAGE.into(), highlights: || tree_sitter_scala::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "scheme", aliases: &["scm"], language: || tree_sitter_scheme::LANGUAGE.into(), highlights: || tree_sitter_scheme::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "sdml", aliases: &[], language: || tree_sitter_sdml::LANGUAGE.into(), highlights: || tree_sitter_sdml::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "sql", aliases: &["mysql", "sqlite", "psql", "plsql"], language: || tree_sitter_sequel::LANGUAGE.into(), highlights: || tree_sitter_sequel::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "tsql", aliases: &["mssql", "t-sql"], language: || tree_sitter_sequel_tsql::LANGUAGE.into(), highlights: || tree_sitter_sequel_tsql::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "apex", aliases: &["cls", "trigger"], language: || tree_sitter_sfapex::apex::LANGUAGE.into(), highlights: || tree_sitter_sfapex::apex::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "soql", aliases: &[], language: || tree_sitter_sfapex::soql::LANGUAGE.into(), highlights: || tree_sitter_sfapex::soql::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "sosl", aliases: &[], language: || tree_sitter_sfapex::sosl::LANGUAGE.into(), highlights: || tree_sitter_sfapex::sosl::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "sflog", aliases: &[], language: || tree_sitter_sfapex::sflog::LANGUAGE.into(), highlights: || tree_sitter_sfapex::sflog::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "starlark", aliases: &["bzl", "bazel", "star", "build"], language: || tree_sitter_starlark::LANGUAGE.into(), highlights: || tree_sitter_starlark::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "svelte", aliases: &[], language: || tree_sitter_svelte_ng::LANGUAGE.into(), highlights: || tree_sitter_svelte_ng::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "svg", aliases: &[], language: || tree_sitter_svg::LANGUAGE.into(), highlights: || tree_sitter_svg::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "swift", aliases: &[], language: || tree_sitter_swift::LANGUAGE.into(), highlights: || tree_sitter_swift::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "sysml", aliases: &[], language: || tree_sitter_sysml::LANGUAGE.into(), highlights: || tree_sitter_sysml::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "systemverilog", aliases: &["sv", "verilog", "v"], language: || tree_sitter_systemverilog::LANGUAGE.into(), highlights: || include_str!("../../queries/systemverilog.scm").into() },
    Grammar { id: "templ", aliases: &[], language: || tree_sitter_templ::LANGUAGE.into(), highlights: || include_str!("../../queries/templ.scm").into() },
    Grammar { id: "tlaplus", aliases: &["tla"], language: || tree_sitter_tlaplus::LANGUAGE.into(), highlights: || tree_sitter_tlaplus::HIGHLIGHT_QUERY.into() },
    Grammar { id: "tmux", aliases: &[], language: || tree_sitter_tmux::LANGUAGE.into(), highlights: || tree_sitter_tmux::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "toml", aliases: &[], language: || tree_sitter_toml_ng::LANGUAGE.into(), highlights: || tree_sitter_toml_ng::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "tsquery", aliases: &["query", "scm-query"], language: || tree_sitter_tsquery::LANGUAGE.into(), highlights: || tree_sitter_tsquery::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "typescript", aliases: &["ts", "mts", "cts"], language: || tree_sitter_typescript::LANGUAGE_TYPESCRIPT.into(), highlights: || format!("{}\n{}", tree_sitter_typescript::HIGHLIGHTS_QUERY, tree_sitter_javascript::HIGHLIGHT_QUERY) },
    Grammar { id: "tsx", aliases: &[], language: || tree_sitter_typescript::LANGUAGE_TSX.into(), highlights: || format!("{}\n{}\n{}", tree_sitter_typescript::HIGHLIGHTS_QUERY, tree_sitter_javascript::HIGHLIGHT_QUERY, tree_sitter_javascript::JSX_HIGHLIGHT_QUERY) },
    Grammar { id: "varlink", aliases: &[], language: || tree_sitter_varlink::LANGUAGE.into(), highlights: || tree_sitter_varlink::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "vhdl", aliases: &["vhd"], language: || tree_sitter_vhdl::LANGUAGE.into(), highlights: || tree_sitter_vhdl::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "vue", aliases: &[], language: || tree_sitter_vue_next::LANGUAGE.into(), highlights: || include_str!("../../queries/vue.scm").into() },
    Grammar { id: "xml", aliases: &["xsd", "xsl", "xslt", "plist", "rss", "atom"], language: || tree_sitter_xml::LANGUAGE_XML.into(), highlights: || tree_sitter_xml::XML_HIGHLIGHT_QUERY.into() },
    Grammar { id: "dtd", aliases: &[], language: || tree_sitter_xml::LANGUAGE_DTD.into(), highlights: || tree_sitter_xml::DTD_HIGHLIGHT_QUERY.into() },
    Grammar { id: "yaml", aliases: &["yml"], language: || tree_sitter_yaml::LANGUAGE.into(), highlights: || tree_sitter_yaml::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "zig", aliases: &[], language: || tree_sitter_zig::LANGUAGE.into(), highlights: || tree_sitter_zig::HIGHLIGHTS_QUERY.into() },
    Grammar { id: "zsh", aliases: &[], language: || tree_sitter_zsh::LANGUAGE.into(), highlights: || tree_sitter_zsh::HIGHLIGHT_QUERY.into() },
];
